/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: 'var(--color-background-primary)',
        'background-secondary': 'var(--color-background-secondary)',
        'background-elevated': 'var(--color-background-elevated)',
        surface: 'var(--color-background-secondary)',
        foreground: 'var(--color-text-primary)',
        'text-primary': 'var(--color-text-primary)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-tertiary': 'var(--color-text-tertiary)',
        'text-disabled': 'var(--color-text-disabled)',
        muted: 'var(--color-text-tertiary)',
        border: 'var(--color-border-default)',
        'border-subtle': 'var(--color-border-subtle)',
        'border-strong': 'var(--color-border-strong)',
        accent: 'var(--color-action-primary)',
        'action-primary': 'var(--color-action-primary)',
        'action-secondary': 'var(--color-action-secondary)',
        'focus-ring': 'var(--color-focus-default)',
        'status-success': 'var(--color-status-success-text)',
        'status-success-bg': 'var(--color-status-success-bg)',
        'status-success-border': 'var(--color-status-success-border)',
        'status-error': 'var(--color-status-error-text)',
        'status-error-bg': 'var(--color-status-error-bg)',
        'status-error-border': 'var(--color-status-error-border)',
        'status-warning': 'var(--color-status-warning-text)',
        'status-warning-bg': 'var(--color-status-warning-bg)',
        'status-warning-border': 'var(--color-status-warning-border)',
        'status-info': 'var(--color-status-info-text)',
        'status-info-bg': 'var(--color-status-info-bg)',
        'status-info-border': 'var(--color-status-info-border)',
      },
      fontFamily: {
        sans: ['"General Sans"', '"Inter"', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'Roboto', 'sans-serif'],
        grotesk: ['"General Sans"', '"Inter"', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        display: ['var(--font-size-display-xl)', { lineHeight: 'var(--line-height-display-xl)', letterSpacing: 'var(--letter-spacing-display)' }],
        'heading-section': ['var(--font-size-display-lg)', { lineHeight: 'var(--line-height-display-lg)', letterSpacing: 'var(--letter-spacing-heading)' }],
        'heading-project': ['var(--font-size-display-md)', { lineHeight: 'var(--line-height-display-md)', letterSpacing: 'var(--letter-spacing-subheading)' }],
        'body-editorial': ['var(--font-size-body-editorial)', { lineHeight: 'var(--line-height-body-editorial)', letterSpacing: '-0.015em' }],
        metadata: ['var(--font-size-metadata)', { lineHeight: 'var(--line-height-metadata)', letterSpacing: 'var(--letter-spacing-meta-wide)' }],
      },
      letterSpacing: {
        'display': 'var(--letter-spacing-display)',
        'heading': 'var(--letter-spacing-heading)',
        'subheading': 'var(--letter-spacing-subheading)',
        'normal': '0em',
        'meta': '0.08em',
        'meta-wide': '0.14em',
      },
      borderRadius: {
        'xs': 'var(--radius-xs)',
        'sm': 'var(--radius-sm)',
        'md': 'var(--radius-md)',
        'lg': 'var(--radius-lg)',
        'xl': 'var(--radius-xl)',
        'full': 'var(--radius-full)',
      },
      spacing: {
        'gutter': 'var(--grid-gutter)',
        'page-desktop': 'var(--page-padding-desktop)',
        'page-mobile': 'var(--page-padding-mobile)',
      },
      gridTemplateColumns: {
        'desktop-12': 'repeat(12, minmax(0, 1fr))',
        'tablet-8': 'repeat(8, minmax(0, 1fr))',
        'mobile-4': 'repeat(4, minmax(0, 1fr))',
      }
    },
  },
  plugins: [],
}
